### ISSUE TITLE
clock change from 24 to 12 hr

### ISSUE THREAD

**Issue by ruhulayaan** [htilburgs/MMM-MyPrayerTimes#1]
Hi, How can i change time format from 24 hrs to 12 hrs

**Comment by htilburgs** [comment]
@ruhulayaan, sorry for the late response. I had not seen this issue.
Currently this is not possible. I will look into this.

**Comment by htilburgs** [comment]
@ruhulayaan, added the option for 12/24 hour clock.
Go to ~/MagicMirror/modules/MMM-MyPrayerTimes and do a "git pull" for new version.
After that, reload your MagicMirror.
