### ISSUE TITLE
Module Not Working!

### ISSUE THREAD

**Issue by mh989** [htilburgs/MMM-MyPrayerTimes#11]
So when I added this module to the config file and booted up the MagicMirror, it constantly shows an error and doesn't properly boot up the MagicMirror properly. I think this error occurs because there is something wrong with the MMM-MyPrayerTimes module's configuration. This happens when the configuration is as shown below:
{
module: 'MMM-MyPrayerTimes',
position: 'top_left',
header: 'My Prayer Times',
config: {
mptLat: null, // Replace with the latitude of your location
mptLon: null, // Replace with the Longitude of your location
mptMethod: 3, // Which calculation methode is used, see options below
mptOffset: "0,0,0,0,0,0,0,0,0" // Time corrections for your location: Imsak, Fajr, Sunrise, Duhr, Asr, Sunset, Maghrib, Isha, Midnight
showSunrise: true, // Display Sunrise, false if you want to hide
showSunset: true, // Display Sunset, false if you want to hide
showMidnight: true, // Display Midnight, false if you want to hide
showImsak: true, // Display Imsak, false if you want to hide
show24Clock: true, // Default display 24hour clock -> false is 12hour (AM/PM) clock
}
},

However, if I take out a few things, it begins to work properly and the MagicMirror boots up properly because there isn't an issue with the module. This occurs when the configuration looks like this:

{
module: 'MMM-MyPrayerTimes',
position: 'top_left',
header: 'My Prayer Times',
config: {
mptLat: null, // Replace with the latitude of your location
mptLon: null, // Replace with the Longitude of your location
mptMethod: 3, // Which calculation methode is used, see options below
mptOffset: "0,0,0,0,0,0,0,0,0" // Time corrections for your location: Imsak, Fajr, Sunrise, Duhr, Asr, Sunset, Maghrib, Isha, Midnight
}
},

**Comment by mh989** [comment]
I forgot to add that I do replace the null in the mptLat and mptLon with the proper with my latitude and longitude coordinates for each scenario, and the second one is the one that works.

**Comment by ausheikh** [comment]
it just says loading for me, is there a format for the lat and long that needs to be followed?

**Comment by tanveerahmed22584** [comment]
Hi i am new to this, should i be removing the null and update my cordinates as i am getting a config file error, and the magic mirror is not loading

**Comment by tanveerahmed22584** [comment]
Hi, even for me it says loading but nothing is coming up if i follow as per mh989, kindly advise

**Comment by awadain** [comment]
here is the correct one:
{
 		 module: "MMM-MyPrayerTimes",
  			position: "top_left",
  		header: "My Prayer Times",
  		config: {
        		  mptLat: 48.720737,				// Replace with the latitude of your location
	 		 mptLon: 9.117297,				// Replace with the Longitude of your location
	  		mptMethod: 4,			// Which calculation methode is used, see options below
	 		 mptOffset: "0,0,0,0,0,0,0,0,0",	// Time corrections for your location: Imsak, Fajr, Sunrise, Duhr, Asr, Sunset, Maghrib, Isha, Midnight
	 		 showSunrise: true,			// Display Sunrise, false if you want to hide
	 		 showSunset: false,			// Display Sunset, false if you want to hide
	 		 showMidnight: false,			// Display Midnight, false if you want to hide
	 		 showImsak: false,			// Display Imsak, false if you want to hide
	 		 show24Clock: false			
	  		}
		},

**Comment by abdelhadj** [comment]
Hello, it says loading for me too, any idea how to solve the issue? i copy paste the example.

**Comment by htilburgs** [comment]
There was a problem with package.json.
There was a npm module missing, added request 2.88.2

**Comment by touix974** [comment]
Hello,

It says it is loading...
I have install the package request, but nothing happened. The module stay in loading... mode
