### ISSUE TITLE
Error while loading the module

### ISSUE THREAD

**Issue by touix974** [htilburgs/MMM-MyPrayerTimes#15]
Hello and thank you for your work ! It is very nice to have a prayer time in the mirror.

Unfortunately I encounter an issue when the module is loading :

[11.01.2023 06:50.49.882] [ERROR] Whoops! There was an uncaught exception...
[11.01.2023 06:50.49.898] [ERROR] Error: Cannot find module 'request'
Require stack:
- /MagicMirror/modules/MMM-MyPrayerTimes/node_helper.js

Is there something am doing wrong ?

Thank you for helping.

**Comment by touix974** [comment]
I have install the deprecated module request via the command npm install request.
The error has been corrected.

**Comment by seikomike** [comment]
> I have install the deprecated module request via the command npm install request. The error has been corrected.

Had this (must have) module running for years, before it stopped working. Props to @htilburgs 

You've saved me al lot of time :) 
Thank you barakaloufiek!
