### ISSUE TITLE
Wrong time/Language

### ISSUE THREAD

**Issue by MrGitGo** [htilburgs/MMM-MyPrayerTimes#7]
I have set the mptMethod to 13 - Diyanet İşleri Başkanlığı, Turkey and it gives me the wrong prayer times. Do I have to change something or do updates? And can I change the language to turkish?

**Comment by htilburgs** [comment]
Due to a vacantion and some private issues I react late, sorry for that.
For Turkey it should be mptMethod 13, that's correct.
Did you enter the correct mptLat and mptLong for your location?
The module doesn't support other languages.

**Comment by erkilic** [comment]
Hi MrGitGo, I have the same problem like you with Method 13 (Diyanet). There is a shift of up to 10 minutes. Could you solve the issue?

**Comment by MrGitGo** [comment]
Yes, I could solve it. I did some modifications in the code. I could send it later on.

**Comment by erkilic** [comment]
that would be great. thx in advance. 

gürkan


⁣BlueMail for Android herunterladen ​

**Comment by MrGitGo** [comment]
Here is the .js and .css I hope this works for you as well.
https://www.dropbox.com/s/wtcg4oczngynnv0/MMM-MyPrayerTimes.js?dl=0
https://www.dropbox.com/s/wg0nnjq178nun50/MMM-MyPrayerTimes.css?dl=0

**Comment by htilburgs** [comment]
Thanx for the files.

I will take a look into them next week.

 

Regards, Harm…

 

Van: Proc00 <notifications@github.com> 
Verzonden: donderdag 14 november 2019 10:12
Aan: htilburgs/MMM-MyPrayerTimes <MMM-MyPrayerTimes@noreply.github.com>
CC: Harm Tilburgs <harm@tilburgs.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [htilburgs/MMM-MyPrayerTimes] Wrong time/Language (#7)

 

Here is the .js and .css I hope this works for you as well.
https://www.dropbox.com/s/wtcg4oczngynnv0/MMM-MyPrayerTimes.js?dl=0
https://www.dropbox.com/s/wg0nnjq178nun50/MMM-MyPrayerTimes.css?dl=0

**Comment by htilburgs** [comment]
Thanx for the files.
I will take a look into them next week.

**Comment by htilburgs** [comment]
@MrGitGo , @erkilic 
I've reviewed the files, but I think this is not the way to go.
The MMM-MyPrayerTimes.js is modified and now it is only processing the URL for the Turkish times.
I've decided to go and modify the module:
- Added option for translations (already implemented!)
- Add option to add an offset to the times loaded from the api. (will be implemented soon)

So for now I've put the Turkish translation online (please check if correct).
The next step will be option to add an offset, to correct times.

**Comment by htilburgs** [comment]
@MrGitGo , @erkilic
I've added the **mptOffset** parameter. This gives you the option to correct time differences.
See the readme for the explanation of the mptOffset parameter.

I hope this meets your requirements

**Comment by ilhanaksoy** [comment]
> @MrGitGo , @erkilic I've reviewed the files, but I think this is not the way to go. The MMM-MyPrayerTimes.js is modified and now it is only processing the URL for the Turkish times. I've decided to go and modify the module:
> 
> * Added option for translations (already implemented!)
> * Add option to add an offset to the times loaded from the api. (will be implemented soon)
> 
> So for now I've put the Turkish translation online (please check if correct). The next step will be option to add an offset, to correct times.

Hi @htilburgs , I have checked the turkish translations, Here are my suggestions for improvement:

`{
        "IMSAK": "İmsak",
	"FAJR": "Fecr",
	"SUNRISE": "Gün doğumu",
	"DHUHR": "Öğle",
	"ASR": "İkindi",
	"SUNSET": "Gün batımı",
	"MAGHRIB": "Akşam",
	"ISHA": "Yatsı",
	"MIDNIGHT": "Gece yarısı"
}`
