### ISSUE TITLE
Does not work with following steps

### ISSUE THREAD

**Issue by alomar-mac** [htilburgs/MMM-MyPrayerTimes#9]
I tried a lot and did not succeed with strictly following all instructions and repeated a lot and did not succeed
The matter is important and it seems necessary

Thank You

**Comment by htilburgs** [comment]
Please let me know what is you’re issue.
Explain what is going wrong.

**Comment by alomar-mac** [comment]
First of all thank you fast response
The problem when pasting Configuration to MagicMirror/config
the MagicMirror Never work at all with trying to edit  MMM-MyPrayerTimes Configuration
also i am flowing the steps of Module configuration what you include 
regards

**Comment by alomar-mac** [comment]
Thank you 
it is working good with this Configuration in MagicMirror/config

{
			module: 'MMM-MyPrayerTimes',
			position: 'top_left',
			header: 'My Prayer Times',
			config: {
			 }
		},

**Comment by htilburgs** [comment]
With the config you provided, I cannot imagen that it works. Several importang parameters are missing:

> {
>   module: 'MMM-MyPrayerTimes',
>   position: 'top_left',
>   header: 'My Prayer Times',
>   config: {
>           mptLat: **null,**				// Replace with the latitude of your location
> 	  mptLon: **null,**				// Replace with the Longitude of your location
> 	  mptMethod: **3,**			// Which calculation methode is used, see options below
> 	  mptOffset: "0,0,0,0,0,0,0,0,0"	// Time corrections for your location: Imsak, Fajr, Sunrise, Duhr, Asr, Sunset, Maghrib, Isha, Midnight
> 	  showSunrise: true,			// Display Sunrise, false if you want to hide
> 	  showSunset: true,			// Display Sunset, false if you want to hide
> 	  showMidnight: true,			// Display Midnight, false if you want to hide
> 	  showImsak: true,			// Display Imsak, false if you want to hide
> 	  show24Clock: true,			// Default display 24hour clock -> false is 12hour (AM/PM) clock
> 	  }
> },

The 3 items I marked **BOLD** (mptLat, mptLon, mptMethod) in the upper configuration are needed to make it work properly.
To get your latitude and longitude, you can go to [https://latitudelongitude.org](https://latitudelongitude.org )

**Comment by alomar-mac** [comment]
I just Completed the parameters in  MagicMirror/modules/MMM-MyPrayerTimes/MMM-MyPrayerTimes.js

like this 

defaults: {
		date: new Date(),			// Today
		mptLat: 26.313589,				// Replace null with your Latitude
		mptLon: 50.206001, 				// Replace null with your Longitude
		mptMethod: 4,

**Comment by htilburgs** [comment]
Ok, thanks for the reply and succes!
Enjoy MMM-MyPrayerTimes!
